# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objinput',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 15, 44, 23, 207549)),
        ),
    ]
