# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0005_auto_20171016_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objinput',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 18, 44, 0, 98662)),
        ),
    ]
